btcconf:
  ip: "localhost"
  port: "8332"      
  user: "Rennbon"  
  passwd: "qwe123456"
  env: 3
mongo:
  addr: "localhost:27017"
  timeout: 30
  poolLimit: 500
  database: "blockChain"
xlmconf:
  env: 3
ethconf:
  host: "ws://127.0.0.1:8485"